name: Go
permissions:
  contents: read
  pull-requests: write
on:
  pull_request:
  push:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-26]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: stable
          cache: true
      - run: make
      - run: make test
